version: '3.8'
services:
  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql_server
    env_file:
      - .env
    ports:
      - "1433:1433"
    #networks:
    #    - project-network

  # frontend:
  #    build:
  #      context: ./frontend
  #    ports:
  #      - "3000:3000"
  #    depends_on:
  #      - backend
     #networks:
       #- project-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
   # networks:
     # - project-network
    
#networks:
 # project-network:
  #  driver: bridge
