version: '3.8'
services:
  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql_server
    environment:
      SA_PASSWORD: "MyP@ssw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    #networks:
    #    - project-network

  frontend:
     build:
       context: ./frontend
     ports:
       - "5173:5173"
     depends_on:
       - backend
    # networks:
     #  - project-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
   # networks:
     # - project-network
    
#networks:
 # project-network:
  #  driver: bridge
